DATA:
  DATASET: agri420k
  IMG_SIZE: 224
MODEL:
  TYPE: efficientnet_v2
  NAME: efficientnet_v2_s
  EFFICIENTNET_V2:
    NAME: efficientnet_v2_s
    DROPOUT: 0.1
    STOCHASTIC_DEPTH: 0.2
SAVE_FREQ: 50
