DATA:
  DATASET: agri420k
  IMG_SIZE: 224
MODEL:
  TYPE: convnext
  NAME: convnext_small
  DROP_PATH_RATE: 0.2
  CONVNEXT:
    DIMS: [96, 192, 384, 768]
    DEPTHS: [ 3, 3, 27, 3]
    LAYER_SCALE_INIT_VALUE: 1e-6
SAVE_FREQ: 50
