DATA:
  DATASET: agri420k
  IMG_SIZE: 224
MODEL:
  TYPE: pvt
  NAME: pvtv2_b0
  PVT:
    PATCH_SIZE: 4
    EMBED_DIMS: [32, 64, 160, 256]
    NUM_HEADS: [1, 2, 5, 8]
    MLP_RATIOS: [8, 8, 4, 4]
    QKV_BIAS: True
    DEPTHS: [2, 2, 2, 2]
    SR_RATIOS: [8, 4, 2, 1]
    # DROP_RATE: 0.
    # ATTN_DROP_RATE: 0.
    # DROP_PATH_RATE: 0.
    # PYT.NUM_STAGES: 4
    # LINEAR: False
SAVE_FREQ: 50
