DATA:
  DATASET: agri420k
  IMG_SIZE: 224
MODEL:
  TYPE: convnext
  NAME: convnext_small_ft
  DROP_PATH_RATE: 0.2
  CONVNEXT:
    DIMS: [96, 192, 384, 768]
    DEPTHS: [ 3, 3, 27, 3]
    LAYER_SCALE_INIT_VALUE: 1e-6
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
SAVE_FREQ: 15
