DATA:
  DATASET: agri420k
  IMG_SIZE: 224
MODEL:
  TYPE: efficientnet_v2
  NAME: efficientnet_v2_l_ft
  EFFICIENTNET_V2:
    NAME: efficientnet_v2_l
    DROPOUT: 0.1
    STOCHASTIC_DEPTH: 0.2
TRAIN:
  EPOCHS: 10
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
SAVE_FREQ: 15


