DATA:
  DATASET: agri420k
  IMG_SIZE: 224
MODEL:
  TYPE: vit
  NAME: vit_l_32_224_ft
  VIT:
    PATCHES: 32
    EMBED_DIM: 1024
    FEEDFORWARD_DIM: 4096
    NUM_HEADS: 16
    NUM_LAYERS: 24
    ATTENTION_DROPOUT_RATE: 0.0
    DROPOUT_RATE: 0.1
    REPRESENTATION_SIZE: 1024
    CLASSIFIER: 'token'
    POSITIONAL_EMBEDDING: '1d'
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
SAVE_FREQ: 15
